### ISSUE TITLE
gitopen does not work properly

### ISSUE THREAD

**Issue by gaowhen** [hotoo/gitopen#39]
We have our own gitlab server . 

There is a remote called `upstream` in .git/config

The .gitopenrc is

```
gitlab.x.xx.com:
  type: custom
  protocol: http
```

the `gitopen` command opens a url like this `http://gitlab.x.xx.com/[:username]/[:repository]undefined`

the `gitopen mr/pr` command pops a list without the `upstream/master`

**Comment by hotoo** [comment]
```
  type: gitlab
```

**Comment by gaowhen** [comment]
`gitopen` works, but when use `gitopen mr` there is still no `upstrea/master` in the list

**Comment by hotoo** [comment]
show me the `git branch -r`

**Comment by gaowhen** [comment]
```  
 gaojing/library
  gaojing/master
  gaojing/new_movie
  github/master
  origin/HEAD -> origin/master
  origin/master
  origin/movie-detail
  origin/workflow
  upstream/master
```

**Comment by hotoo** [comment]
Use arrow key (Down) for show more remote branches.

**Comment by gaowhen** [comment]
I know, but that's the whole list.

**Comment by hotoo** [comment]
OK, I know the problem:

`gitopen mr` will passed over the same name of current working branch (cwb), and you cwb is the master branch.

**Comment by hotoo** [comment]
```
https://github.com/eggjs/eslint-config-egg/compare/master...hotoo:doc/trailing-commas?expand=1

baseUrl/compare/baseBranch...headUser:headBranch?expand=1
```

**Comment by hotoo** [comment]
https://github.com/hotoo/gitopen/pull/69
