### ISSUE TITLE
`gitopen pr` chooses incorrect base branch

### ISSUE THREAD

**Issue by sjdemartini** [hotoo/gitopen#52]
The regular expression appears to be incorrect for determining the base branch for a repo. 

A way to reproduce this is as follows:
- Merge a branch which has a commit name that includes square brackets. e.g., `[foo] This is my commit message`
- On another branch, run `gitopen pr` and notice that the URL sets the base branch as `foo`, somehow pulling that out as the base branch based on the above merged commit with the bracketed `[foo]` in the commit message

P.S. Thanks for making `gitopen`. Really useful tool! Hope we can fix this issue, since this is an important feature in your tool over https://github.com/paulirish/git-open.

**Comment by hotoo** [comment]
gitopen@2.7.2 fixed this, thank you.

**Comment by sjdemartini** [comment]
Thank you! I appreciate the quick fix.
