### ISSUE TITLE
Support XDG_CONFIG_HOME or way to change config path

### ISSUE THREAD

**Issue by derimagia** [hotoo/gitopen#62]
I don't see a way to change the config path currently. Would be good to follow the XDG config spec: 

https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
https://wiki.archlinux.org/index.php/XDG_Base_Directory_support

Essentially if XDG_CONFIG_HOME is set it'll use that as the base path and then add /git or /gitopen to it. 

Git already uses this and will get your config if you have it set - $XDG_CONFIG_HOME/git/config / $XDG_CONFIG_HOME/git/ignore

**Comment by hotoo** [comment]
PR is welcome 👍
